# Generated by Django 4.2.3 on 2023-11-19 05:21

import alpha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=alpha.models.upload_path)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
